# Generated by Django 4.2.26 on 2025-11-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryitem',
            name='category',
            field=models.CharField(choices=[('A', 'Статья'), ('N', 'Новость')], default='N', max_length=1),
        ),
    ]
