# Generated by Django 4.2.26 on 2025-11-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_dictionaryitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionaryitem',
            name='category',
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='name',
            field=models.CharField(choices=[('T', 'Модель техники'), ('E', 'Модель двигателя')], max_length=1),
        ),
    ]
