# Generated by Django 4.2.26 on 2025-11-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_dictionary_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
