# Generated by Django 4.2.26 on 2025-11-09 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Наработка, м/час')),
                ('downtime_hours', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Время простоя техники')),
                ('description_of_failure', models.TextField(verbose_name='Описание отказа')),
                ('spare_parts_used', models.TextField(blank=True, null=True, verbose_name='Используемые запасные части')),
                ('date_of_failure', models.DateField(verbose_name='Дата отказа')),
                ('date_of_restoration', models.DateField(blank=True, null=True, verbose_name='Дата восстановления')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('failure_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_failure_node', to='common.dictionaryitem', verbose_name='Узел отказа')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamation_records', to='machines.machine', verbose_name='Машина')),
                ('restoration_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_restoration_method', to='common.dictionaryitem', verbose_name='Способ восстановления')),
                ('service_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_by_service_company', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
            ],
            options={
                'verbose_name': 'Рекламация',
                'verbose_name_plural': 'Рекламации',
                'ordering': ['-date_of_failure'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Наработка, м/час')),
                ('work_order_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='№ заказ-наряда')),
                ('date_of_maintenance', models.DateField(verbose_name='Дата проведения ТО')),
                ('date_work_order', models.DateField(blank=True, null=True, verbose_name='Дата заказ-наряда')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='machines.machine', verbose_name='Машина')),
                ('organization_performing_maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_performing_org', to='common.dictionaryitem', verbose_name='Организация, проводившая ТО')),
                ('service_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_by_service_company', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
                ('type_of_maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_type', to='common.dictionaryitem', verbose_name='Вид ТО')),
            ],
            options={
                'verbose_name': 'Техническое обслуживание',
                'verbose_name_plural': 'Технические обслуживания',
                'ordering': ['-date_of_maintenance'],
            },
        ),
    ]
