# Generated by Django 4.2.26 on 2025-11-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='date_of_failure',
            field=models.DateTimeField(verbose_name='Дата отказа'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='date_of_restoration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата восстановления'),
        ),
    ]
