# Generated by Django 4.2.26 on 2025-11-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_records', '0002_alter_reclamation_date_of_failure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='downtime_hours',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Время простоя техники, ч'),
        ),
    ]
