# Generated by Django 4.2.26 on 2025-11-12 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0005_alter_dictionary_name'),
        ('service_records', '0004_alter_reclamation_downtime_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='organization_performing_maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_performing_org', to='common.dictionaryitem', verbose_name='Организация, проводившая ТО'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='service_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_by_service_company', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='type_of_maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_type', to='common.dictionaryitem', verbose_name='Вид ТО'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='failure_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamations_failure_node', to='common.dictionaryitem', verbose_name='Узел отказа'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='restoration_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamations_restoration_method', to='common.dictionaryitem', verbose_name='Способ восстановления'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='service_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamations_by_service_company', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания'),
        ),
    ]
