# Generated by Django 4.2.26 on 2025-11-09 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number_machine', models.CharField(max_length=100, unique=True, verbose_name='Зав. № машины')),
                ('serial_number_engine', models.CharField(blank=True, max_length=100, null=True, verbose_name='Зав. № двигателя')),
                ('serial_number_transmission', models.CharField(blank=True, max_length=100, null=True, verbose_name='Зав. № трансмиссии')),
                ('serial_number_drive_axle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Зав. № ведущего моста')),
                ('serial_number_steered_axle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Зав. № управляемого моста')),
                ('delivery_contract', models.CharField(blank=True, max_length=100, null=True, verbose_name='Договор поставки №, дата')),
                ('consignee', models.CharField(blank=True, max_length=255, null=True, verbose_name='Грузополучатель')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Адрес поставки (эксплуатации)')),
                ('complexation', models.TextField(blank=True, null=True, verbose_name='Комплектация (доп. опции)')),
                ('date_dispatch_from_factory', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('date_delivery_contract', models.DateField(blank=True, null=True, verbose_name='Дата договора поставки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines_as_client', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('model_drive_axle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines_model_drive_axle', to='common.dictionaryitem')),
                ('model_engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines_model_engine', to='common.dictionaryitem')),
                ('model_steered_axle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines_model_steered_axle', to='common.dictionaryitem')),
                ('model_technique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines_model_technique', to='common.dictionaryitem')),
                ('model_transmission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines_model_transmission', to='common.dictionaryitem')),
                ('service_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines_as_service_company', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
                'ordering': ['-date_dispatch_from_factory'],
            },
        ),
    ]
