# Generated by Django 4.2.26 on 2025-11-09 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_dictionaryitem_category'),
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='model_drive_axle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines_model_drive_axle', to='common.dictionaryitem', verbose_name='Модель ведущего моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='model_engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines_model_engine', to='common.dictionaryitem', verbose_name='Модель двигателя'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='model_steered_axle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines_model_steered_axle', to='common.dictionaryitem', verbose_name='Модель управляемого моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='model_technique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines_model_technique', to='common.dictionaryitem', verbose_name='Модель техники'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='model_transmission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines_model_transmission', to='common.dictionaryitem', verbose_name='Модель трансмиссии'),
        ),
    ]
