# Generated by Django 4.2.26 on 2025-11-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_alter_machine_model_drive_axle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='serial_number_machine',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Зав. № машины'),
        ),
    ]
