# Generated by Django 4.2.26 on 2025-11-12 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('machines', '0003_alter_machine_serial_number_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machines_as_service_company', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания'),
        ),
    ]
